# Generated by Django 3.0.7 on 2020-06-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramProfile',
        ),
    ]
