# Generated by Django 3.0.7 on 2020-06-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_telegramprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
