# Generated by Django 3.0.7 on 2020-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(allow_unicode=True, default='', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
