# Generated by Django 3.0.7 on 2020-06-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_profile', '0002_telegramprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramprofile',
            name='name',
        ),
    ]
