# Generated by Django 3.0.7 on 2020-06-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_profile', '0006_telegramprofile_nme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramprofile',
            old_name='nme',
            new_name='name',
        ),
    ]
