# Generated by Django 3.0.7 on 2020-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(blank=True, upload_to='recipe_pics'),
        ),
    ]
