# Generated by Django 3.0.7 on 2020-06-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200627_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_pic',
            new_name='recipe_image',
        ),
    ]
